### ISSUE TITLE
Read CBR/CBZ file on web is gone

### ISSUE THREAD

**Issue by nzeminski** [linuxserver/docker-calibre-web#63]
When attempting to read a CBR or CBZ file, the only button available is to download the file.
![image](https://user-images.githubusercontent.com/60979973/74357171-85e00500-4d8d-11ea-88b8-2f33ce128338.png)

I used to be able to read them inside the web browser.

**Comment by nzeminski** [comment]
As opposed to linuxserver/calibre-web:amd64-0.6.4-ls44 running on version 0.6.4, I have the Read in browser button.
![image](https://user-images.githubusercontent.com/60979973/74358174-03584500-4d8f-11ea-8372-5cd2f6aee81d.png)

**Comment by CHBMB** [comment]
@nzeminski Can't help you unless you fill out the template.  Need to be able to reproduce things accurately to test.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.



------------------------------

## Expected Behavior


## Current Behavior


## Steps to Reproduce


1.
2.
3.
4.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**      


## Command used to create docker container (run/create/compose/screenshot)


## Docker logs

**Comment by nzeminski** [comment]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.



------------------------------

## Expected Behavior
Reading comics, CBR or CBZ files, a "Read in browser" button shows to read file in web browser

## Current Behavior
Only download button is available. No "Read in browser".

## Steps to Reproduce


1. Click on comicbook to read
2. Only download button appears.
3. "Read in browser" button is available in version 0.6.4
4.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**      

Ubuntu 18.04.4
x86_64
docker
## Command used to create docker container (run/create/compose/screenshot)

docker create --name=calibre-web --restart=always --network=host \
-v /valhalla/downloads/books/calibre:/books \
-v /opt/calibre-web:/calibre-web/config \
-e USE_CONFIG_DIR=true \
-e DOCKER_MODS=linuxserver/calibre-web:calibre \
-e SET_CONTAINER_TIMEZONE=true \
-e CONTAINER_TIMEZONE=America/New_York \
-e PGID=999 -e PUID=1001 \
-p 8083:8083 \
linuxserver/calibre-web
## Docker logs

[docker.log](https://github.com/linuxserver/docker-calibre-web/files/4194342/docker.log)

**Comment by nzeminski** [comment]
Oops, I'm an idiot. I didn't realize the change with user permissions and adding 'Allow book viewer'.
